server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**